sudo: required
dist: xenial
services:
  - docker

before_script:
  - mkdir /tmp/basket
  - mv * /tmp/basket
  - cd .ci

script:
  - docker build -t basket_bd .
  - docker run -it -v /tmp/basket:/home/root basket_bd